name: Deploy CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image And Push
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/codin-frontend:latest --push -f ./docker/Dockerfile .

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            echo ${{ secrets.PASSWORD }} | sudo -S su -c "
              docker ps -a
              docker rm -f codin-frontend || true
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/codin-frontend:latest
              docker run -d --net codin-main_default -p 3000:3000 --name codin-frontend ${{ secrets.DOCKERHUB_USERNAME }}/codin-frontend:latest
              docker images -f "dangling=true" -q | xargs sudo docker rmi || true
              docker ps -a
            "
